version: '3.7'
services:
  typo3-web:
    build:
      context: .
      dockerfile: Dockerfile
#    image: effectiveworld/centos6-php7
    container_name: web_drupal_demo
    depends_on:
      - drupal-db
#      - ipso-memcache
#    networks:
#      - ipso_lan
    ports:
      - "80:8080"
    volumes:
### Mount or override configurations for PHP, Apache and MySQL
      - ./docker/conf/php73.ini:/etc/opt/remi/php73/php.ini
      - ./docker/conf/00-default.conf:/etc/httpd/conf/vhosts.d/00-default.conf
#      - ./docker/conf/rewriterules.config:/etc/httpd/conf.d/rewriterules.config
      - ./docker/conf/dbadmin2.conf:/etc/httpd/conf.d/dbadmin2.conf
      - ./docker/conf/phpmyadmin_config.inc.php:/etc/phpMyAdmin/config.inc.php
### Mount project files
      - ./:/var/www/project
#      - ./views:/var/www/project/views
    command: ["/usr/sbin/httpd", "-DFOREGROUND"]
  drupal-db:
    image: mysql:5.7
    container_name: db_drupal_demo
    environment:
### Password for the MySQL root user
      MYSQL_ROOT_PASSWORD: "devel"
    ports:
      - "3306:3306"
#    volumes:
#      - ipso_db:/var/lib/mysql
#      - ./docker/conf/ipso_db.conf:/etc/mysql/conf.d/ipso_db.conf
#    networks:
#      - ipso_lan
#networks:
#  ipso_lan:
### Remove the comment to use external network (i.e. outside of Compose)
#   external: true
#volumes:
#  ipso_db:
### TBD: Whether to use cross-projects DB store
#    external: true
